#========== server config =======
server:
  port: 8080
  servlet:
    context-path: /

#=========== data source =========
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/octopus?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456


#=========== log config ====================
logging:
  level:
    root: info
    org:
      lvgo: debug
    druid:
      sql:
        Statement: debug



